In [28]:
## Import libraries
import numpy as np
import pandas as pd
from sklearn.grid_search import GridSearchCV
import time



from sklearn.cross_validation import train_test_split
from sklearn.cross_validation import StratifiedShuffleSplit


# Read student data
student_data = pd.read_csv("students_data.csv")
print("Student data read successfully!")
# Note: The last column 'passed' is the target/label, all other are feature columns

Student data read successfully!

In [29]:
student_data.head()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,internet,romantic,famrel,freetime,goout,Dalc,Walc,health,absences,passed
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,no,no,4,3,4,1,1,3,6,no
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,yes,no,5,3,3,1,1,3,4,no
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,yes,no,4,3,2,2,3,3,10,yes
3,GP,F,15,U,GT3,T,4,2,health,services,...,yes,yes,3,2,2,1,1,5,2,yes
4,GP,F,16,U,GT3,T,3,3,other,other,...,no,no,4,3,2,1,2,5,4,yes

In [30]:
len(student_data)

395

In [31]:
student_data.shape

(395, 31)

In [32]:
student_data[student_data['passed'] == 'yes']

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,internet,romantic,famrel,freetime,goout,Dalc,Walc,health,absences,passed
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,yes,no,4,3,2,2,3,3,10,yes
3,GP,F,15,U,GT3,T,4,2,health,services,...,yes,yes,3,2,2,1,1,5,2,yes
4,GP,F,16,U,GT3,T,3,3,other,other,...,no,no,4,3,2,1,2,5,4,yes
5,GP,M,16,U,LE3,T,4,3,services,other,...,yes,no,5,4,2,1,2,5,10,yes
6,GP,M,16,U,LE3,T,2,2,other,other,...,yes,no,4,4,4,1,1,3,0,yes
8,GP,M,15,U,LE3,A,3,2,services,other,...,yes,no,4,2,2,1,1,1,0,yes
9,GP,M,15,U,GT3,T,3,4,other,other,...,yes,no,5,5,1,1,1,5,0,yes
11,GP,F,15,U,GT3,T,2,1,services,other,...,yes,no,5,2,2,1,1,4,4,yes
12,GP,M,15,U,LE3,T,4,4,health,services,...,yes,no,4,3,3,1,3,5,2,yes
13,GP,M,15,U,GT3,T,4,3,teacher,other,...,yes,no,5,4,3,1,2,3,2,yes
14,GP,M,15,U,GT3,A,2,2,other,other,...,yes,yes,4,5,2,1,1,3,0,yes
15,GP,F,16,U,GT3,T,4,4,health,other,...,yes,no,4,4,4,1,2,2,4,yes
16,GP,F,16,U,GT3,T,4,4,services,services,...,yes,no,3,2,3,1,2,2,6,yes
17,GP,F,16,U,GT3,T,3,3,other,other,...,no,no,5,3,2,1,1,4,4,yes
19,GP,M,16,U,LE3,T,4,3,health,other,...,yes,no,3,1,3,1,3,5,4,yes
20,GP,M,15,U,GT3,T,4,3,teacher,other,...,yes,no,4,4,1,1,1,1,0,yes
21,GP,M,15,U,GT3,T,4,4,health,health,...,yes,no,5,4,2,1,1,5,0,yes
22,GP,M,16,U,LE3,T,4,2,teacher,other,...,yes,no,4,5,1,1,3,5,2,yes
23,GP,M,16,U,LE3,T,2,2,other,other,...,yes,no,5,4,4,2,4,5,0,yes
26,GP,M,15,U,GT3,T,2,2,other,other,...,yes,no,4,2,2,1,2,5,2,yes
27,GP,M,15,U,GT3,T,4,2,health,services,...,yes,no,2,2,4,2,4,1,4,yes
28,GP,M,16,U,LE3,A,3,4,services,other,...,yes,no,5,3,3,1,1,5,4,yes
29,GP,M,16,U,GT3,T,4,4,teacher,teacher,...,yes,yes,4,4,5,5,5,5,16,yes
30,GP,M,15,U,GT3,T,4,4,health,services,...,yes,no,5,4,2,3,4,5,0,yes
31,GP,M,15,U,GT3,T,4,4,services,services,...,yes,no,4,3,1,1,1,5,0,yes
32,GP,M,15,R,GT3,T,4,3,teacher,at_home,...,yes,yes,4,5,2,1,1,5,0,yes
33,GP,M,15,U,LE3,T,3,3,other,other,...,yes,no,5,3,2,1,1,2,0,yes
34,GP,M,16,U,GT3,T,3,2,other,other,...,yes,no,5,4,3,1,1,5,0,yes
36,GP,M,15,U,LE3,T,4,3,teacher,services,...,yes,no,5,4,3,1,1,4,2,yes
37,GP,M,16,R,GT3,A,4,4,other,teacher,...,yes,yes,2,4,3,1,1,5,7,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
348,GP,F,17,U,GT3,T,4,3,health,other,...,yes,yes,4,4,3,1,3,4,0,yes
349,MS,M,18,R,GT3,T,3,2,other,other,...,yes,no,2,5,5,5,5,5,10,yes
351,MS,M,17,U,GT3,T,3,3,health,other,...,yes,no,4,5,4,2,3,3,2,yes
354,MS,M,17,R,GT3,T,4,3,services,other,...,yes,yes,4,5,5,1,3,2,4,yes
356,MS,F,17,R,GT3,T,4,4,teacher,services,...,yes,no,4,3,3,1,2,5,4,yes
357,MS,F,17,U,LE3,A,3,2,services,other,...,no,yes,1,2,3,1,2,5,2,yes
358,MS,M,18,U,LE3,T,1,1,other,services,...,yes,yes,3,3,2,1,2,3,4,yes
359,MS,F,18,U,LE3,T,1,1,at_home,services,...,yes,no,5,3,2,1,1,4,0,yes
360,MS,F,18,R,LE3,A,1,4,at_home,other,...,no,yes,4,3,4,1,4,5,0,yes
361,MS,M,18,R,LE3,T,1,1,at_home,other,...,no,no,4,4,3,2,3,5,2,yes
362,MS,F,18,U,GT3,T,3,3,services,services,...,yes,yes,4,3,2,1,3,3,0,yes
363,MS,F,17,U,LE3,T,4,4,at_home,at_home,...,yes,yes,2,3,4,1,1,1,0,yes
364,MS,F,17,R,GT3,T,1,2,other,services,...,no,no,3,2,2,1,2,3,0,yes
365,MS,M,18,R,GT3,T,1,3,at_home,other,...,no,no,3,3,4,2,4,3,4,yes
366,MS,M,18,U,LE3,T,4,4,teacher,services,...,yes,yes,4,2,2,2,2,5,0,yes
368,MS,F,18,U,GT3,T,2,3,at_home,services,...,yes,yes,5,2,3,1,2,4,0,yes
369,MS,F,18,R,GT3,T,4,4,other,teacher,...,yes,yes,3,2,2,4,2,5,10,yes
371,MS,M,18,R,LE3,T,1,2,at_home,services,...,yes,yes,4,3,3,2,3,3,3,yes
372,MS,F,17,U,GT3,T,2,2,other,at_home,...,no,yes,3,4,3,1,1,3,8,yes
374,MS,F,18,R,LE3,T,4,4,other,other,...,yes,no,5,4,4,1,1,1,0,yes
375,MS,F,18,R,GT3,T,1,1,other,other,...,yes,no,4,3,2,1,2,4,2,yes
376,MS,F,20,U,GT3,T,4,2,health,other,...,yes,yes,5,4,3,1,1,3,4,yes
377,MS,F,18,R,LE3,T,4,4,teacher,services,...,yes,no,5,4,3,3,4,2,4,yes
378,MS,F,18,U,GT3,T,3,3,other,other,...,yes,yes,4,1,3,1,2,1,0,yes
379,MS,F,17,R,GT3,T,3,1,at_home,other,...,yes,no,4,5,4,2,3,1,17,yes
380,MS,M,18,U,GT3,T,4,4,teacher,teacher,...,yes,no,3,2,4,1,4,2,4,yes
382,MS,M,17,U,GT3,T,2,3,other,services,...,yes,no,4,4,3,1,1,3,2,yes
385,MS,F,18,R,GT3,T,2,2,at_home,other,...,no,no,5,3,3,1,3,4,2,yes
391,MS,M,17,U,LE3,T,3,1,services,services,...,yes,no,2,4,5,3,4,2,3,yes
393,MS,M,18,R,LE3,T,3,2,services,other,...,yes,no,4,4,1,3,4,5,0,yes

In [33]:
# TODO: Compute desired values - replace each '?' with an appropriate expression/function call
n_students = student_data.shape[0]
n_features = student_data.shape[1]
n_passed = student_data[student_data['passed'] == 'yes'].shape[0]
n_failed = student_data[student_data['passed'] == 'no'].shape[0]
grad_rate = n_passed / float(n_students)
print("Total number of students: {}".format(n_students))
print("Number of students who passed: {}".format(n_passed))
print("Number of students who failed: {}".format(n_failed))
print("Number of features: {}".format(n_features))
print("Graduation rate of the class: {:.2f}%".format(grad_rate*100))

Total number of students: 395
Number of students who passed: 265
Number of students who failed: 130
Number of features: 31
Graduation rate of the class: 67.09%

In [34]:
X_all =  student_data[student_data.columns[:-1]]

In [35]:
y_all = student_data[student_data.columns[-1:]]

In [36]:
# Preprocess feature columns
def preprocess_features(X):
    outX = pd.DataFrame(index=X.index)  # output dataframe, initially empty

    # Check each column
    for col, col_data in X.iteritems():
        # If data type is non-numeric, try to replace all yes/no values with 1/0
        if col_data.dtype == object:
            col_data = col_data.replace(['yes', 'no'], [1, 0])
        # Note: This should change the data type for yes/no columns to int

        # If still non-numeric, convert to one or more dummy variables
        if col_data.dtype == object:
            col_data = pd.get_dummies(col_data, prefix=col)  # e.g. 'school' => 'school_GP', 'school_MS'

        outX = outX.join(col_data)  # collect column(s) in output dataframe

    return outX

X_all = preprocess_features(X_all)
print("Processed feature columns ({}):-\n{}".format(len(X_all.columns), list(X_all.columns)))

Processed feature columns (48):-
['school_GP', 'school_MS', 'sex_F', 'sex_M', 'age', 'address_R', 'address_U', 'famsize_GT3', 'famsize_LE3', 'Pstatus_A', 'Pstatus_T', 'Medu', 'Fedu', 'Mjob_at_home', 'Mjob_health', 'Mjob_other', 'Mjob_services', 'Mjob_teacher', 'Fjob_at_home', 'Fjob_health', 'Fjob_other', 'Fjob_services', 'Fjob_teacher', 'reason_course', 'reason_home', 'reason_other', 'reason_reputation', 'guardian_father', 'guardian_mother', 'guardian_other', 'traveltime', 'studytime', 'failures', 'schoolsup', 'famsup', 'paid', 'activities', 'nursery', 'higher', 'internet', 'romantic', 'famrel', 'freetime', 'goout', 'Dalc', 'Walc', 'health', 'absences']

In [37]:
X_all.head()

,school_GP,school_MS,sex_F,sex_M,age,address_R,address_U,famsize_GT3,famsize_LE3,Pstatus_A,...,higher,internet,romantic,famrel,freetime,goout,Dalc,Walc,health,absences
0,1,0,1,0,18,0,1,1,0,1,...,1,0,0,4,3,4,1,1,3,6
1,1,0,1,0,17,0,1,1,0,0,...,1,1,0,5,3,3,1,1,3,4
2,1,0,1,0,15,0,1,0,1,0,...,1,1,0,4,3,2,2,3,3,10
3,1,0,1,0,15,0,1,1,0,0,...,1,1,1,3,2,2,1,1,5,2
4,1,0,1,0,16,0,1,1,0,0,...,1,0,0,4,3,2,1,2,5,4

In [38]:
def reformat(col_data):
    return col_data.replace(['yes', 'no'], [1, 0])

In [39]:
X_all.head()

,school_GP,school_MS,sex_F,sex_M,age,address_R,address_U,famsize_GT3,famsize_LE3,Pstatus_A,...,higher,internet,romantic,famrel,freetime,goout,Dalc,Walc,health,absences
0,1,0,1,0,18,0,1,1,0,1,...,1,0,0,4,3,4,1,1,3,6
1,1,0,1,0,17,0,1,1,0,0,...,1,1,0,5,3,3,1,1,3,4
2,1,0,1,0,15,0,1,0,1,0,...,1,1,0,4,3,2,2,3,3,10
3,1,0,1,0,15,0,1,1,0,0,...,1,1,1,3,2,2,1,1,5,2
4,1,0,1,0,16,0,1,1,0,0,...,1,0,0,4,3,2,1,2,5,4

In [40]:
from sklearn.cross_validation import train_test_split

In [41]:
X_train, X_test, y_train, y_test = train_test_split(X_all, y_all, test_size=0.20, random_state=42)

In [42]:
# Train a model
import time

def train_classifier(clf, X_train, y_train):
    print("Training {}...".format(clf.__class__.__name__))
    start = time.time()
    clf.fit(X_train, y_train)
    end = time.time()
    diff = end - start
    print("Done!\nTraining time (secs): {:.3f}".format(diff))
    return diff

In [43]:
from sklearn.ensemble import RandomForestClassifier

rf_clf = RandomForestClassifier(n_estimators=50)

# Fit model to training data
train_classifier(rf_clf, X_train, y_train)  # note: using entire training set here
print(rf_clf)  # you can inspect the learned model by printing it

Training RandomForestClassifier...
Done!
Training time (secs): 0.111
RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=50, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

/usr/local/lib/python3.5/dist-packages/ipykernel_launcher.py:7: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  import sys

In [44]:
# Predict on training set and compute F1 score
from sklearn.metrics import f1_score

def predict_labels(clf, features, target):
    print("Predicting labels using {}...".format(clf.__class__.__name__))
    start = time.time()
    y_pred = clf.predict(features)
    end = time.time()
    prediction_time_diff = end - start
    print("Done!\nPrediction time (secs): {:.3f}".format(prediction_time_diff))
    return(y_pred)

#return (f1_score(target.values, y_pred, pos_label='yes'), prediction_time_diff)
train_f1_score = predict_labels(rf_clf, X_test, y_test)

Predicting labels using RandomForestClassifier...
Done!
Prediction time (secs): 0.010

In [45]:
f1_accuracy_random_forest = f1_score(list(y_test['passed']),list(train_f1_score),pos_label='yes')

In [46]:
f1_accuracy_random_forest

0.77049180327868849

In [47]:
def train_classifier(clf, X_train, y_train):
    ''' Fits a classifier to the training data. '''
    
    # Start the clock, train the classifier, then stop the clock
    start = time.time()
    clf.fit(X_train, y_train)
    end = time.time()
    
    # Print the results
    print("Trained model in {:.4f} seconds".format(end - start))

In [48]:
def predict_labels(clf, features, target):
    ''' Makes predictions using a fit classifier based on F1 score. '''
    
    # Start the clock, make predictions, then stop the clock
    start = time.time()
    y_pred = clf.predict(features)
    end = time.time()
    
    # Print and return results
    print("Made predictions in {:.4f} seconds.".format(end - start))
    return f1_score(target.values, y_pred, pos_label='yes')

In [49]:
def train_predict(clf, X_train, y_train, X_test, y_test):
    ''' Train and predict using a classifer based on F1 score. '''
    
    # Indicate the classifier and the training set size
    print("Training a {} using a training set size of {}. . .".format(clf.__class__.__name__, len(X_train)))
    
    # Train the classifier
    train_classifier(clf, X_train, y_train)
    
    # Print the results of prediction for both training and testing
    print("F1 score for training set: {:.4f}.".format(predict_labels(clf, X_train, y_train)))
    print("F1 score for test set: {:.4f}.".format(predict_labels(clf, X_test, y_test)))
    print("\n")

In [50]:
# TODO: Import the three supervised learning models from sklearn
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression
import time

In [51]:
# TODO: Initialize the three models
clf_A = RandomForestClassifier()
clf_B = GaussianNB()
clf_C = LogisticRegression()

In [52]:
# TODO: Set up the training set sizes
# Previously shuffled
X_train_100 = X_train[:100]
y_train_100 = y_train[:100]

X_train_200 = X_train[:200]
y_train_200 = y_train[:200]

X_train_300 = X_train
y_train_300 = y_train

In [53]:
for clf in [clf_A, clf_B, clf_C]:
    for j in [(X_train_100, y_train_100), (X_train_200, y_train_200), (X_train_300, y_train_300)]:
        train_predict(clf,j[0],j[1], X_test, y_test)

Training a RandomForestClassifier using a training set size of 100. . .
Trained model in 0.0161 seconds
Made predictions in 0.0016 seconds.
F1 score for training set: 0.9839.
Made predictions in 0.0020 seconds.
F1 score for test set: 0.7290.


Training a RandomForestClassifier using a training set size of 200. . .
Trained model in 0.0163 seconds
Made predictions in 0.0026 seconds.
F1 score for training set: 0.9888.
Made predictions in 0.0017 seconds.
F1 score for test set: 0.7966.


Training a RandomForestClassifier using a training set size of 316. . .
Trained model in 0.0179 seconds
Made predictions in 0.0034 seconds.
F1 score for training set: 0.9906.
Made predictions in 0.0017 seconds.
F1 score for test set: 0.7027.


Training a GaussianNB using a training set size of 100. . .
Trained model in 0.0032 seconds
Made predictions in 0.0007 seconds.
F1 score for training set: 0.8244.
Made predictions in 0.0008 seconds.
F1 score for test set: 0.7568.


Training a GaussianNB using a training set size of 200. . .
Trained model in 0.0025 seconds
Made predictions in 0.0008 seconds.
F1 score for training set: 0.8151.
Made predictions in 0.0006 seconds.
F1 score for test set: 0.7222.


Training a GaussianNB using a training set size of 316. . .
Trained model in 0.0044 seconds
Made predictions in 0.0010 seconds.
F1 score for training set: 0.8064.
Made predictions in 0.0005 seconds.
F1 score for test set: 0.7636.


Training a LogisticRegression using a training set size of 100. . .
Trained model in 0.0018 seconds
Made predictions in 0.0006 seconds.
F1 score for training set: 0.8769.
Made predictions in 0.0004 seconds.
F1 score for test set: 0.7586.


Training a LogisticRegression using a training set size of 200. . .
Trained model in 0.0034 seconds
Made predictions in 0.0006 seconds.
F1 score for training set: 0.8541.
Made predictions in 0.0004 seconds.
F1 score for test set: 0.7931.


Training a LogisticRegression using a training set size of 316. . .
Trained model in 0.0133 seconds
Made predictions in 0.0005 seconds.
F1 score for training set: 0.8362.
Made predictions in 0.0004 seconds.
F1 score for test set: 0.8070.

/usr/local/lib/python3.5/dist-packages/ipykernel_launcher.py:6: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.5/dist-packages/ipykernel_launcher.py:6: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.5/dist-packages/ipykernel_launcher.py:6: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/lib/python3/dist-packages/sklearn/utils/validation.py:515: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/lib/python3/dist-packages/sklearn/utils/validation.py:515: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/lib/python3/dist-packages/sklearn/utils/validation.py:515: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/lib/python3/dist-packages/sklearn/utils/validation.py:515: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/lib/python3/dist-packages/sklearn/utils/validation.py:515: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/lib/python3/dist-packages/sklearn/utils/validation.py:515: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [54]:
# Models 4 - 7 for general comparison

# TODO: Import the three supervised learning models from sklearn
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import SGDClassifier


# TODO: Initialize the three models
clf_A = DecisionTreeClassifier(random_state=0)
clf_B = SGDClassifier(random_state=0)
clf_C = SVC(random_state=0)
clf_D = KNeighborsClassifier()

# TODO: Set up the training set sizes
# Previously shuffled
X_train_100 = X_train[:100]
y_train_100 = y_train[:100]

X_train_200 = X_train[:200]
y_train_200 = y_train[:200]

X_train_300 = X_train
y_train_300 = y_train

# TODO: Execute the 'train_predict' function for each classifier and each training set size
for clf in [clf_A, clf_B, clf_C, clf_D]:
    for j in [(X_train_100, y_train_100), (X_train_200, y_train_200), (X_train_300, y_train_300)]:
        train_predict(clf, j[0], j[1], X_test, y_test)

Training a DecisionTreeClassifier using a training set size of 100. . .
Trained model in 0.0047 seconds
Made predictions in 0.0005 seconds.
F1 score for training set: 1.0000.
Made predictions in 0.0004 seconds.
F1 score for test set: 0.7091.


Training a DecisionTreeClassifier using a training set size of 200. . .
Trained model in 0.0032 seconds
Made predictions in 0.0007 seconds.
F1 score for training set: 1.0000.
Made predictions in 0.0009 seconds.
F1 score for test set: 0.6857.


Training a DecisionTreeClassifier using a training set size of 316. . .
Trained model in 0.0054 seconds
Made predictions in 0.0006 seconds.
F1 score for training set: 1.0000.
Made predictions in 0.0006 seconds.
F1 score for test set: 0.7523.


Training a SGDClassifier using a training set size of 100. . .
Trained model in 0.0013 seconds
Made predictions in 0.0006 seconds.
F1 score for training set: 0.7972.
Made predictions in 0.0006 seconds.
F1 score for test set: 0.7863.


Training a SGDClassifier using a training set size of 200. . .
Trained model in 0.0014 seconds
Made predictions in 0.0004 seconds.
F1 score for training set: 0.7988.
Made predictions in 0.0004 seconds.
F1 score for test set: 0.7939.


Training a SGDClassifier using a training set size of 316. . .
Trained model in 0.0018 seconds
Made predictions in 0.0076 seconds.
F1 score for training set: 0.5096.
Made predictions in 0.0003 seconds.
F1 score for test set: 0.4533.


Training a SVC using a training set size of 100. . .
Trained model in 0.0029 seconds
Made predictions in 0.0018 seconds.
F1 score for training set: 0.8936.
Made predictions in 0.0017 seconds.
F1 score for test set: 0.7603.


Training a SVC using a training set size of 200. . .
Trained model in 0.0079 seconds
Made predictions in 0.0058 seconds.
F1 score for training set: 0.8664.
Made predictions in 0.0026 seconds.
F1 score for test set: 0.7907.


Training a SVC using a training set size of 316. . .
Trained model in 0.0164 seconds
Made predictions in 0.0130 seconds.
F1 score for training set: 0.8671.
Made predictions in 0.0037 seconds.
F1 score for test set: 0.7874.


Training a KNeighborsClassifier using a training set size of 100. . .
Trained model in 0.0012 seconds
Made predictions in 0.0026 seconds.
F1 score for training set: 0.8148.
Made predictions in 0.0023 seconds.
F1 score for test set: 0.7377.


Training a KNeighborsClassifier using a training set size of 200. . .
Trained model in 0.0016 seconds
Made predictions in 0.0100 seconds.
F1 score for training set: 0.8611.
Made predictions in 0.0033 seconds.
F1 score for test set: 0.7742.


Training a KNeighborsClassifier using a training set size of 316. . .
Trained model in 0.0019 seconds
Made predictions in 0.0148 seconds.
F1 score for training set: 0.8701.
Made predictions in 0.0030 seconds.
F1 score for test set: 0.7899.

/usr/lib/python3/dist-packages/sklearn/utils/validation.py:515: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/lib/python3/dist-packages/sklearn/utils/validation.py:515: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/lib/python3/dist-packages/sklearn/utils/validation.py:515: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/lib/python3/dist-packages/sklearn/svm/base.py:514: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y_ = column_or_1d(y, warn=True)
/usr/lib/python3/dist-packages/sklearn/svm/base.py:514: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y_ = column_or_1d(y, warn=True)
/usr/lib/python3/dist-packages/sklearn/svm/base.py:514: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y_ = column_or_1d(y, warn=True)
/usr/local/lib/python3.5/dist-packages/ipykernel_launcher.py:6: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().

/usr/local/lib/python3.5/dist-packages/ipykernel_launcher.py:6: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().

/usr/local/lib/python3.5/dist-packages/ipykernel_launcher.py:6: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().

In [55]:
# Models 4 - 7 for general comparison

# TODO: Import the three supervised learning models from sklearn
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import SGDClassifier


# TODO: Initialize the three models
clf_A = DecisionTreeClassifier(random_state=0)
clf_B = SGDClassifier(random_state=0)
clf_C = SVC(random_state=0)
clf_D = KNeighborsClassifier()

# TODO: Set up the training set sizes
# Previously shuffled
X_train_100 = X_train[:100]
y_train_100 = y_train[:100]

X_train_200 = X_train[:200]
y_train_200 = y_train[:200]

X_train_300 = X_train
y_train_300 = y_train

# TODO: Execute the 'train_predict' function for each classifier and each training set size
for clf in [clf_A, clf_B, clf_C, clf_D]:
    for j in [(X_train_100, y_train_100), (X_train_200, y_train_200), (X_train_300, y_train_300)]:
        train_predict(clf, j[0], j[1], X_test, y_test)

Training a DecisionTreeClassifier using a training set size of 100. . .
Trained model in 0.0026 seconds
Made predictions in 0.0005 seconds.
F1 score for training set: 1.0000.
Made predictions in 0.0008 seconds.
F1 score for test set: 0.7091.


Training a DecisionTreeClassifier using a training set size of 200. . .
Trained model in 0.0034 seconds
Made predictions in 0.0007 seconds.
F1 score for training set: 1.0000.
Made predictions in 0.0006 seconds.
F1 score for test set: 0.6857.


Training a DecisionTreeClassifier using a training set size of 316. . .
Trained model in 0.0051 seconds
Made predictions in 0.0025 seconds.
F1 score for training set: 1.0000.
Made predictions in 0.0011 seconds.
F1 score for test set: 0.7523.


Training a SGDClassifier using a training set size of 100. . .
Trained model in 0.0019 seconds
Made predictions in 0.0004 seconds.
F1 score for training set: 0.7972.
Made predictions in 0.0006 seconds.
F1 score for test set: 0.7863.


Training a SGDClassifier using a training set size of 200. . .
Trained model in 0.0029 seconds
Made predictions in 0.0104 seconds.
F1 score for training set: 0.7988.
Made predictions in 0.0004 seconds.
F1 score for test set: 0.7939.


Training a SGDClassifier using a training set size of 316. . .
Trained model in 0.0037 seconds
Made predictions in 0.0009 seconds.
F1 score for training set: 0.5096.
Made predictions in 0.0004 seconds.
F1 score for test set: 0.4533.


Training a SVC using a training set size of 100. . .
Trained model in 0.0031 seconds
Made predictions in 0.0020 seconds.
F1 score for training set: 0.8936.
Made predictions in 0.0015 seconds.
F1 score for test set: 0.7603.


Training a SVC using a training set size of 200. . .
Trained model in 0.0075 seconds
Made predictions in 0.0055 seconds.
F1 score for training set: 0.8664.
Made predictions in 0.0024 seconds.
F1 score for test set: 0.7907.


Training a SVC using a training set size of 316. . .
Trained model in 0.0163 seconds
Made predictions in 0.0128 seconds.
F1 score for training set: 0.8671.
Made predictions in 0.0035 seconds.
F1 score for test set: 0.7874.


Training a KNeighborsClassifier using a training set size of 100. . .
Trained model in 0.0012 seconds
Made predictions in 0.0026 seconds.
F1 score for training set: 0.8148.
Made predictions in 0.0023 seconds.
F1 score for test set: 0.7377.


Training a KNeighborsClassifier using a training set size of 200. . .
Trained model in 0.0015 seconds
Made predictions in 0.0066 seconds.
F1 score for training set: 0.8611.
Made predictions in 0.0034 seconds.
F1 score for test set: 0.7742.


Training a KNeighborsClassifier using a training set size of 316. . .
Trained model in 0.0020 seconds
Made predictions in 0.0230 seconds.
F1 score for training set: 0.8701.
Made predictions in 0.0049 seconds.
F1 score for test set: 0.7899.

/usr/lib/python3/dist-packages/sklearn/utils/validation.py:515: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/lib/python3/dist-packages/sklearn/utils/validation.py:515: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/lib/python3/dist-packages/sklearn/utils/validation.py:515: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/lib/python3/dist-packages/sklearn/svm/base.py:514: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y_ = column_or_1d(y, warn=True)
/usr/lib/python3/dist-packages/sklearn/svm/base.py:514: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y_ = column_or_1d(y, warn=True)
/usr/lib/python3/dist-packages/sklearn/svm/base.py:514: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y_ = column_or_1d(y, warn=True)
/usr/local/lib/python3.5/dist-packages/ipykernel_launcher.py:6: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().

/usr/local/lib/python3.5/dist-packages/ipykernel_launcher.py:6: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().

/usr/local/lib/python3.5/dist-packages/ipykernel_launcher.py:6: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().

In [56]:
# TODO: Import 'GridSearchCV' and 'make_scorer'
from sklearn.grid_search import GridSearchCV
from sklearn.metrics import make_scorer

In [80]:

# TODO: Import 'GridSearchCV' and 'make_scorer'
from sklearn.grid_search import GridSearchCV
from sklearn.metrics import make_scorer

def predict_labels(clf, features, target):
    ''' Makes predictions using a fit classifier based on F1 score. '''
    
    # Start the clock, make predictions, then stop the clock
    start = time.time()
    y_pred = clf.predict(features)
    score = clf.score(features, target.values)
    end = time.time()
    print("Score: ", score)
    
    # Print and return results
    print("Made predictions in {:.4f} seconds.".format(end - start))
    return f1_score(target.values, y_pred, pos_label='yes')


# TODO: Create the parameters list you wish to tune
parameters = { "penalty":["l2"], 
              # "tol":[0.00001, 0.0001, 0.001, 0.1, 1], 
               "C":[0.1,0.75,1,10],
              }

# TODO: Initialize the classifier
clf = LogisticRegression()

# TODO: Make an f1 scoring function using 'make_scorer' 
f1_scorer = make_scorer(f1_score, pos_label='yes')

# TODO: Perform grid search on the classifier using the f1_scorer as the scoring method
grid_obj = GridSearchCV(clf, parameters, scoring=f1_scorer)

# TODO: Fit the grid search object to the training data and find the optimal parameters
grid_obj = grid_obj.fit(X_train, list(y_train["passed"]))
print(grid_obj)
# Get the estimator
clf = grid_obj.best_estimator_
print(clf)

# Report the final F1 score for training and testing after parameter tuning
print("Tuned model has a training F1 score of {:.4f}.".format(predict_labels(clf, X_train, y_train)))
print("Tuned model has a testing F1 score of {:.4f}.".format(predict_labels(clf, X_test, y_test)))

GridSearchCV(cv=None, error_score='raise',
       estimator=LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False),
       fit_params={}, iid=True, n_jobs=1,
       param_grid={'penalty': ['l2'], 'C': [0.5, 0.75, 1, 10]},
       pre_dispatch='2*n_jobs', refit=True,
       scoring=make_scorer(f1_score, pos_label=yes), verbose=0)
LogisticRegression(C=0.5, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)
Score:  0.759493670886
Made predictions in 0.0022 seconds.
Tuned model has a training F1 score of 0.8369.
Score:  0.73417721519
Made predictions in 0.0009 seconds.
Tuned model has a testing F1 score of 0.8174.

In [73]:
grid_obj

GridSearchCV(cv=None, error_score='raise',
       estimator=LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False),
       fit_params={}, iid=True, n_jobs=1,
       param_grid={'penalty': ['l2'], 'C': [1, 10, 100, 1000]},
       pre_dispatch='2*n_jobs', refit=True,
       scoring=make_scorer(f1_score, pos_label=yes), verbose=0)

In [74]:
grid_obj.best_estimator_

LogisticRegression(C=1, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)